{
  "openapi": "3.0.0",
  "info": {
    "sdk_desc": "update_product_example",
    "sdk_version": "2.7.10",
    "version": "v2",
    "title": "Merchent APIs",
    "description": "SallaSDK offers developers seamless integration and interaction with the Salla platform's APIs, enabling the creation of customized e-commerce solutions with ease and efficiency.\n",
    "termsOfService": "https://salla.sa/site/terms/",
    "contact": {
      "name": "Salla",
      "url": "https://www.salla.sa",
      "email": "support@salla.dev"
    }
  },
  "servers": [
    {
      "url": "https://api.salla.dev/admin/v2",
      "description": "Production"
    }
  ],
  "paths": {
    "/customers": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "List Customers",
        "description": "You can list all customers related to your store directly from this endpoint. Also, it allows you to filter them using a keyword, the endpoint would retrieve any customer matches this keyword in their data whether in their mobile number or email or name.",
        "operationId": "List-Customers",
        "security": [
          {
            "OAuth": [
              "CustomersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "Create Customer",
        "description": "Customers can be created within your store at Salla by providing the required data in this endpoint. \n\nYou may need the [Countries List](https://docs.salla.dev/docs/merchant/b3A6ODUwMzM4-list-countries) endpoint to get the mobile and country codes.\n\nAlso, you may use the [Customer Groups list](https://docs.salla.dev/docs/merchant/b3A6NTU1NzcwNg-list-customer-groups) to add the group's IDs for the new customer. Kindly note that customer's email and mobile number are un[...]",
        "operationId": "Create-Customer",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/customers/{customer}": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "Customer Details",
        "description": "you can return a specific customer's Details by providing the ID of the customer you want to get his details in the *customer* path parameter.",
        "operationId": "Customer-Details",
        "security": [
          {
            "OAuth": [
              "CustomersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "Update Customer",
        "description": "Update a customer using this Endpoint. Provide the ID of the customer you want to update in the *customer* path parameter. The response will be all the customer updated data.\n\n>💡 __Note__\n>\n> The existing value of all skipped parameters will remain unchanged.",
        "operationId": "Update-Customer",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "Delete Customer",
        "description": "Delete a customer from the store customers list by providing the ID of the customer you want to delete in the *customer* path parameter.",
        "operationId": "Delete-Customer",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/customers/blacklist/{customer}": {
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "Ban Customer",
        "description": "You can use this endpoint to ban (Add to blacklist) one of your customers by providing the ID of the customer you want to ban in the *customer* path parameter.\n\nBanned customer won't be able to create new orders. \n\n>💡 __Note__\n>\n>Banned customers can login to the store.",
        "operationId": "Ban-Customer",
        "security": [],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "Un-Ban customer",
        "description": "You can use this endpoint to ub-ban (remove from blacklist) one of banned customers by providing the ID of the customer you want to un ban in the *customer* path parameter.",
        "operationId": "Un-ban-Customer",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/customers/groups": {
      "get": {
        "tags": [
          "Customer Groups"
        ],
        "summary": "List Customer Groups",
        "description": "This endpoint allows you to list all the customer groups in your store. Customer groups are aiming to divide customers into smaller groups instead of the default customers group to be able to serve them better and to determine their needs and also give each group special treatment.",
        "operationId": "List-Groups",
        "security": [
          {
            "OAuth": [
              "CustomersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Customer Groups"
        ],
        "summary": "Create Group",
        "description": "This Endpoint allows you to create customer groups by providing the group name which is required and the conditions (similarities between group members) and the features that the group members will have.\n\n**type** may be one of these \n1. total_sales\n2. total_orders\n3. store_rating\n4. doesnt_have_orders\n \nand the **symbols** may be one of these\n1. '>'\n2. '<'\n3. 'between'\n\n>💡 __Note__\n>\n>To add the payment methods you will need to get the payment methods list[...]",
        "operationId": "Create-Group",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/customers/groups/add_customers": {
      "post": {
        "tags": [
          "Customer Groups"
        ],
        "summary": "Add Customers To Group Customers",
        "description": "This endpoint allows you to add customers to a specific customer groups.",
        "operationId": "post-customers-groups-add_customers",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/customers/groups/default": {
      "post": {
        "tags": [
          "Customer Groups"
        ],
        "summary": "Update Default Group",
        "description": "Each new customer is added automatically to the default customer group, You can update the default customer group from this Endpoint\n\n>💡 __Note__\n>\n>You can change only group features ( payment methods - shipping methods )",
        "operationId": "Update-Default-Group",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/customers/groups/{group}": {
      "put": {
        "tags": [
          "Customer Groups"
        ],
        "summary": "Update Group",
        "description": "This Endpoint allows you to update a customer group by providing the ID of the group you want to update in the *group* path parameter.",
        "operationId": "Update-Group",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Customer Groups"
        ],
        "summary": "Delete Group",
        "description": "This Endpoint allows you to delete a customer group by providing the ID of the group you want to delete in the *group* path parameter.\n\n\n>💡 __Note__\n>\n>Group members will be removed automatically from this group only.",
        "operationId": "Delete-Group",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/customers/import": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "Import Customers",
        "description": "This endpoint allows you to import products from an Excel file. Check this [article](https://help.salla.sa/article/1082536000) for more.\n\n",
        "operationId": "post-customers-import",
        "security": [
          {
            "OAuth": [
              "CustomersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/webhooks/subscribe": {
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Register Webhook",
        "description": "Registering a new webhook is to notify/update/delete an external service when an event has occurred. \n\nTo trigger your webhook to send data, You can choose one event from the list of events which You can get from the [List Events](https://docs.salla.dev/docs/merchent/ZG9jOjI0NTE3NDg1-webhook#list-of-events) Endpoint. \n\n>💡 __Note__\n>\n> ✅ New subscriptions with the same URL and event updates/restore old webhooks (if exist) <br>\n> ✅ Added URL must allow POST requests [...]",
        "operationId": "Create-webhook",
        "security": [
          {
            "OAuth": [
              "WebhooksReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/webhooks": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "List Active Webhooks",
        "description": "This endpoint allows you to list all available, registered, and active webhooks related to the store.\n\n",
        "operationId": "get-webhooks",
        "security": [
          {
            "OAuth": [
              "WebhooksReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/webhooks/events": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "List Events",
        "description": "You can list all the available events that can be used in registering webhooks from this endpoint.\n\nLook more into Webhook Events from [here](https://docs.salla.dev/docs/merchent/ZG9jOjI0NTE3NDg1-webhook#list-of-events).",
        "operationId": "List-Events",
        "security": [
          {
            "OAuth": [
              "WebhooksReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/webhooks/unsubscribe": {
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Deactivate Webhook",
        "description": "This endpoint allows you to unsubscribe/deactivate a webhook from the active webhooks list at your store. \n\nYou can define which webhook to delete by using `url` and/or `id` query parameters.\n\nUsing `url` will delete all registered webhooks to this URL.",
        "operationId": "Delete-webhook",
        "security": [
          {
            "OAuth": [
              "WebhooksReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/carts/abandoned": {
      "get": {
        "tags": [
          "Abandoned Carts"
        ],
        "summary": "List Abandoned Carts",
        "description": "An abandoned cart occurs when a customer adds an item to their cart and didn't complete the purchase.\n\nSalla helps you by providing a list of abandoned carts that contains all the needed data that you can use to help customers continue the purchasing process.",
        "operationId": "List-Abandoned-Carts",
        "security": [
          {
            "OAuth": [
              "CartsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/taxes": {
      "get": {
        "tags": [
          "Taxes"
        ],
        "summary": "List Taxes",
        "description": "This endpoint allows you to list all available taxes for your store.",
        "operationId": "List-Taxes",
        "security": [
          {
            "OAuth": [
              "TaxesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Taxes"
        ],
        "summary": "Create Tax",
        "description": "This endpoint allows you to create a new tax and return the corresponding tax id.\n\nYou must add tax rate and specify which country that tax will be applied to by providing a country id.\n\n>Note: you can get country id from [List Countries](../~1countries/get) Endpoint.",
        "operationId": "Create-Tax",
        "security": [
          {
            "OAuth": [
              "TaxesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/taxes/{tax}": {
      "get": {
        "tags": [
          "Taxes"
        ],
        "summary": "Tax Details",
        "description": "This endpoint allows you to return the complete details for specific tax by providing the ID of the tax you want to get its details in the *tax* path parameter.",
        "operationId": "Tax-Details",
        "security": [
          {
            "OAuth": [
              "TaxesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Taxes"
        ],
        "summary": "Update Tax",
        "description": "This endpoint allows you to update an existing tax by providing the ID of the tax you want to update in the *tax* path parameter.",
        "operationId": "Update-Tax",
        "security": [
          {
            "OAuth": [
              "TaxesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Taxes"
        ],
        "summary": "Delete Tax",
        "description": "This endpoint allows you to delete an existing tax by providing the ID of the tax you want to delete in the *tax* path parameter.",
        "operationId": "Delete-Tax",
        "security": [
          {
            "OAuth": [
              "TaxesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "List Orders",
        "description": "You can list all orders related to your store directly from this endpoint. Also, it allows you to filter them using a different set of optional parameters.",
        "operationId": "List-Orders",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Create Order",
        "description": "This endpoint allows you to create an order related to your store directly from this endpoint.\n\n<!-- theme: info -->\n\n> 💡 __Note__\n>\n> When creating an order, you must send either the `customer_id` variable or the `receiver` object, or both.",
        "operationId": "Create-Order",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}/status": {
      "post": {
        "tags": [
          "Order Status"
        ],
        "summary": "Update Order Status",
        "description": "This endpoint allows you to update the status for a specific order by providing the ID of the order in the *order* path parameter.\nAlso you should pass either the status ID or the slug.\n\n>💡 __Note__\n>\n> To update an order status, you may use one of the following:\n> - `slug` to update an order with predefined Salla statuses.\n> - `status_id` to update the Custom Order Sub-status.",
        "operationId": "Update-Order-Status",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/statuses": {
      "get": {
        "tags": [
          "Order Status"
        ],
        "summary": "List Order Statuses",
        "description": "This endpoint allows you to fetch a list of all order statuses and sub-statuses.",
        "operationId": "List-Order-Statuses",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Order Status"
        ],
        "summary": "Create Custom Sub-Status",
        "description": "This endpoint allows you to create a custom order status using the parameters available to be sent as body request.",
        "operationId": "post-orders-statuses-status",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/statuses/{status_id}": {
      "get": {
        "tags": [
          "Order Status"
        ],
        "summary": "Order Status Details",
        "description": "This endpoint allows you to fetch details about a specific order status by passing its ID.",
        "operationId": "get-orders-statuses-status_id",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Order Status"
        ],
        "summary": "Update Statuses",
        "description": "This endpoint allows you to update a custom order status using the parameters available to be sent as body request. ",
        "operationId": "put-orders-statuses-status",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}/tags": {
      "post": {
        "tags": [
          "Order Tags"
        ],
        "summary": "Create Tag",
        "description": "You can you can assign specific order with a tag by using the tag name. by providing the ID of the order you want to add this tag to it in the *order.id* path parameter.\n\nYou can get a list of available tags from [List Tags](../~1orders~1tags/get) endpoint.\n\nYou can get a list of orders assigned to a tag from [List Orders](../~1orders/get) endpoint using tag query parameter.",
        "operationId": "Create-Tag",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/tags": {
      "get": {
        "tags": [
          "Order Tags"
        ],
        "summary": "List Tags",
        "description": "This endpoint allows you to list all available tags that already exist so that you could use them in tagging orders.",
        "operationId": "get-tags",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}/tags/{tag_id}": {
      "delete": {
        "tags": [
          "Order Tags"
        ],
        "summary": "Delete Tag",
        "description": "This endpoint allows you to delete a specific tag from a specific order by providing the ID of the tag you want to delete in the *tag.id* path parameter and providing the ID of the order in the *order.id* path parameter.",
        "operationId": "delete-tag",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/invoices": {
      "get": {
        "tags": [
          "Order Invoice"
        ],
        "summary": "List Invoices",
        "description": "This endpoint allows you to fetch a list of order invoices.\n\n",
        "operationId": "get-orders-invoices",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Order Invoice"
        ],
        "summary": "Create Invoice",
        "description": "This endpoint allows you to create an invoice to a specific order from your side, either as an uploaded `file`, path `url`, or ordinary `data` and `order` in your body request.\n\n> 💡 __Note__\n>\n> For the `order` data type, you will need to specify the Invoice issuance to be from Salla. However, for the other data types available, such as `data`, `url`, and `file`, you will need to set it to custom from the [Store Settings](s.salla.sa/settings).",
        "operationId": "post-orders-invoices-order_id-add",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/invoices/{invoice_id}": {
      "get": {
        "tags": [
          "Order Invoice"
        ],
        "summary": "Invoice Details",
        "description": "This endpoint allows you to fetch a specific order invoice.\n\n",
        "operationId": "get-invoice-details",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}/cancel-shipment": {
      "post": {
        "tags": [
          "Order Shipment"
        ],
        "summary": "Cancel Order Shipment",
        "description": "You can cancel specific Order Shipment by providing the ID of the order you want to cancel in the *order.id* path parameter. \n\n> 💡 __Note__\n>\n> You will need to send the parameters in your request: *shipment_number* and *shipment_type*\n\n",
        "operationId": "Cancel-Order-Shipment",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Order Details",
        "description": "This endpoint allows you to return the complete details for a specific order by providing the ID of the order you want to get its details in the *order* path parameter.\n\n> 💡 __Note__\n>\n> You are also able to send the `reference_id` as a *query parameter* to get order details. Check the [List Orders Endpoint](https://docs.salla.dev/docs/merchant/b3A6NTU1NzcyNA-list-orders) for more.",
        "operationId": "Order-Details",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}/histories": {
      "get": {
        "tags": [
          "Order Histories"
        ],
        "summary": "List Order Histories",
        "description": "This endpoint allows you to return the history for a specific order by providing the ID of the order you want to get its history in the *order* path parameter.\n\nOrder history is a list of previous and current order statuses.",
        "operationId": "Order-Histories",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Order Histories"
        ],
        "summary": "Create Order History",
        "description": "This endpoint allows you to append a `note` to the Order History.",
        "operationId": "post-orders-order_id-histories",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}/shipments": {
      "get": {
        "tags": [
          "Order Shipment"
        ],
        "summary": "List Order Shipments",
        "description": "This endpoint allows you to fetch the complete details of a specific Order Shipments by providing the ID of the order you want to get its details in the order path parameter.",
        "operationId": "get-orders-order-shipments",
        "security": [
          {
            "OAuth": [
              "OrdersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/orders/{order_id}/update-shipment": {
      "put": {
        "tags": [
          "Order Shipment"
        ],
        "summary": "Update Order Shipment",
        "description": "You can update specific Order Shipment Details (tracking link, shipment number, pdf label and shipment type) by providing the ID of the order you want to update its details in the *order.id* path parameter.",
        "operationId": "update-order-shipment",
        "security": [
          {
            "OAuth": [
              "OrdersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/payment/methods": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Available Methods",
        "description": "This endpoint allows you to list all available payment methods.",
        "operationId": "Available-Methods",
        "security": [
          {
            "OAuth": [
              "PaymentsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "List Products",
        "description": "You can list all available products related to your store directly from this endpoint. \n\nAlso, it allows you to filter them using a keyword, status, and category parameters. The endpoint would retrieve any product that matches used filters.",
        "operationId": "Get-Products",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Create Product",
        "description": "Products can be created within your store at Salla by providing the required data in this endpoint.\n\nYou can list available categories from [List Categories](https://docs.salla.dev/docs/merchant/0a8f8ce47eeab-list-categories) endpoint.\n\n> 💡 __Note__\n>\n> ✅ Created products status will be `hidden` till attaching one image at least. <br>\n> ✅ Created products status will be `out` till adding a value in quantity parameter. <br>\n> ✅ Created products type cannot be chang[...]",
        "operationId": "Create-Product",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Product Details",
        "description": "You can return specific product Details by providing the ID of the product you want to get its details in the *product* path parameter.\n\n",
        "operationId": "Product-Details",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Products"
        ],
        "summary": "Update Product",
        "description": "You can update specific product Details by providing the ID of the product you want to update its details in the *product* path parameter.\n\n",
        "operationId": "Update-Product",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Products"
        ],
        "summary": "Delete Product",
        "description": "You can delete specific product by providing the ID of the product you want to delete in the *product* path parameter.",
        "operationId": "Delete-Product",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}/status": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Change Product Status",
        "description": "You can update specific product status by providing the ID of the product you want to update its status in the *product* path parameter.",
        "operationId": "Change-Product-Status",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/tags": {
      "get": {
        "tags": [
          "Product Tags"
        ],
        "summary": "List Product Tags",
        "description": "You can list all available product tags related to your store directly from this endpoint.",
        "operationId": "get-products-tags",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Product Tags"
        ],
        "summary": "Create Product Tag",
        "description": "Product Tags can be created within your store at Salla by providing the required data in this endpoint.",
        "operationId": "post-products-tags",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}/digital-codes": {
      "post": {
        "tags": [
          "Digitals Product"
        ],
        "summary": "Attach Digital Code",
        "description": "You can add digital codes to a specific codes product by providing the ID of the product you want to attach these codes to it in the *product* path parameter.\n\n> 💡 __Note__\n>\n> You can attach codes to codes product only.",
        "operationId": "Attach-Digital-Codes",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/sku/{sku}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Product Details By SKU",
        "description": "You can return specific product Details by providing the SKU of the product you want to get its details in the *sku* path parameter.",
        "operationId": "Get-Product-By-SKU",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Products"
        ],
        "summary": "Update Product By SKU",
        "description": "You can update specific product Details by providing the SKU of the product you want to update its details in the *sku* path parameter.",
        "operationId": "Update-Product-By-SKU",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Products"
        ],
        "summary": "Delete Product By SKU",
        "description": "You can delete specific product by providing the SKU of the product you want to delete in the *sku* path parameter.",
        "operationId": "Delete-Product-By-SKU",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/sku/{sku}/price": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Update Product Price By SKU",
        "description": "You can update specific product price by providing the SKU of the product you want to update its price in the *sku* path parameter.",
        "operationId": "Update-Product-Price-By-SKU.",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/sku/{sku}/images": {
      "post": {
        "tags": [
          "Product Images"
        ],
        "summary": "Attach Image by SKU",
        "description": "This endpoint allows you to attach an image by providing the SKU value of the Product. Make sure that you upload a file of image format by sending the body data as `multipart/form-data` \n\n",
        "operationId": "post-products-sku-sku-images",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/sku/{sku}/videos": {
      "post": {
        "tags": [
          "Product Images"
        ],
        "summary": "Attach Video by SKU",
        "description": "This endpoint allows you to attache a video by providing the SKU value of the Product. \n\n",
        "operationId": "post-products-sku-sku-videos",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/quantities/bySku/{sku}": {
      "put": {
        "tags": [
          "Product Quantity"
        ],
        "summary": "Update Quantity By SKU",
        "description": "You can update specific product price by providing the SKU of the product you want to update its price in the *sku* path parameter.",
        "operationId": "Update-quantity-By-SKU",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}/video": {
      "post": {
        "tags": [
          "Product Images"
        ],
        "summary": "Attach Youtube Video",
        "description": "You can add unlimited videos to a specific product by providing the ID of the product you want to attach these videos to it in the *product* path parameter.\n\nYou can add one video only per request.\n\n>💡 __Note__\n>\n> Videos are added as Youtube links.",
        "operationId": "Attach-Youtube-Video",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}/images": {
      "post": {
        "tags": [
          "Product Images"
        ],
        "summary": "Attach Image",
        "description": "You can add up to __10__ images to a specific product by providing the ID of the product you want to attach these images to it in the *product* path parameter. You can do that either via URL link or uploading an image.\n\n> 💡 __Note__\n>\n> You can send one image only per request.",
        "operationId": "Create-Image",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/images/{image-id}": {
      "post": {
        "tags": [
          "Product Images"
        ],
        "summary": "Update Image",
        "description": "This endpoint allows you to update a specific product's image by providing the ID of the image you want to update in the *product* path parameter. The updating of the image can be done either via providing a URL link to the image or uploading an image via `multipart/form-data` media type.\n\n> 💡 __Note__\n>\n> You can update only one image per request.",
        "operationId": "Update-Image",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/images/{image}": {
      "delete": {
        "tags": [
          "Product Images"
        ],
        "summary": "Delete Image",
        "description": "you can delete specific image by providing the ID of that image in *image* path parameter.\n\n>💡 __Note__\n>\n> You can get image ID from product details.",
        "operationId": "Delete-Image",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}/digital-files": {
      "post": {
        "tags": [
          "Digitals Product"
        ],
        "summary": "Attach Digital File",
        "description": "You can add digital files to a specific digital product by providing the ID of the product you want to attach these files to it in the *product* path parameter.\n\nYou can add one digital file only per request.\n\n>💡 __Note__\n>\n> You can attach digital files to digital products only.",
        "operationId": "Attache-Digital-File",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/digital-files/{file}": {
      "delete": {
        "tags": [
          "Digitals Product"
        ],
        "summary": "Delete Digital File",
        "description": "you can delete specific digital file by providing the ID of that file in *file* path parameter.\n\n>**Note**: you can get file ID from product details.",
        "operationId": "Delete-Digital-File",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/quantities/{product}": {
      "put": {
        "tags": [
          "Product Quantity"
        ],
        "summary": "Update Quantity",
        "description": "You can update a specific product quantity by providing the ID of the product you want to update its quantity in the *product* path parameter.",
        "operationId": "Update-quantity",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}/options": {
      "post": {
        "tags": [
          "Product Options"
        ],
        "summary": "Create Option",
        "description": "You can create a new option for a specific product by providing the ID of the product you want to create the option for in the *product* path parameter.\n\n>**Note**: For product.type=product creating new product option will generate a new variant for this option.",
        "operationId": "Create-Option",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/options/{option}": {
      "get": {
        "tags": [
          "Product Options"
        ],
        "summary": "Option Details",
        "description": "You can return specific option details for a specific product by providing the ID of the option you want to return its details in the *option* path parameter.",
        "operationId": "Option-Details",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Product Options"
        ],
        "summary": "Update Product Option",
        "description": "You can update specific option details for a specific product by providing the ID of the option you want to update its details in the *option* path parameter.\n\n>💡 __Note__\n>\n> ✅ For `product.type=product` updating product option with new values will generate new variants for these new values <br>\n> ✅ When `old` values are updated, they are __removed__ as `new` values are added.",
        "operationId": "Update-Option",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Product Option Values"
        ],
        "summary": "Create Value",
        "description": "You can create new values in specific option for a specific product by providing the ID of the option you want to create new values in it in the *option* path parameter.\n\n>💡 __Note__\n>\n> For product.type=product creating new product option value will generate new variant for this new value.",
        "operationId": "Create-Value",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Product Options"
        ],
        "summary": "Delete Option",
        "description": "You can delete specific option for a specific product including its related data (values and variants) by providing the ID of the option you want to delete in the *option* path parameter.",
        "operationId": "Delete-Option",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/options/values/{value}": {
      "get": {
        "tags": [
          "Product Option Values"
        ],
        "summary": "Value Details",
        "description": "You can return value details in specific option for a specific product by providing the ID of the value you want to return its details in the *value* path parameter.",
        "operationId": "Value-Details",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Product Option Values"
        ],
        "summary": "Update Value",
        "description": "You can update value details in specific option for a specific product by providing the ID of the value you want to update its details in the *value* path parameter.",
        "operationId": "Update-Value",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Product Option Values"
        ],
        "summary": "Delete Value",
        "description": "You can delete value from specific option for a specific product by providing the ID of the value you want to delete in the *value* path parameter.",
        "operationId": "Delete-Value",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/prices/bulkPrice": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Update Bulk Product Prices",
        "description": "This endpoint allows you to update **unlimited** bulk products' prices by providing the IDs of the products and the price amount you want to update in your body request, where it will process the update procedure and then execute later on.",
        "operationId": "post-products-prices-bulkPrice",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/{product}/variants": {
      "get": {
        "tags": [
          "Product Variants"
        ],
        "summary": "List Product Variants",
        "description": "You can list all product variants directly from this endpoint. \n\n",
        "operationId": "get-product-variants",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/variants/{variant}": {
      "get": {
        "tags": [
          "Product Variants"
        ],
        "summary": "Show Variant",
        "description": "This endpoint allows you to return the complete details for a specific variant by providing the ID of the variant you want to get its details in the *variant* path parameter.",
        "operationId": "get-products-variants-product",
        "security": [
          {
            "OAuth": [
              "ProductsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Product Variants"
        ],
        "summary": "Update Variant",
        "description": "This endpoint allows you to update variant details by providing the ID of the variant you want to update its details in the *variant* path parameter.",
        "operationId": "update-product-variant",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/quantities/variant/{variant}": {
      "put": {
        "tags": [
          "Product Variants"
        ],
        "summary": "Update Product Variant Quantity",
        "description": "You can update a specific product variant quantity by providing the ID of the variant you want to update its quantity in the *variant* path parameter.",
        "operationId": "update-variant-quantity",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/import": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Import Products",
        "description": "This endpoint allows you to import products from an Excel file. Check this [article](https://help.salla.sa/article/1082536000) for more.\n\n",
        "operationId": "post-products-import",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/quantities/bulk": {
      "post": {
        "tags": [
          "Product Quantity"
        ],
        "summary": "Update Bulk Quantities",
        "description": "You can update **unlimited** bulk quantities by providing the IDs of the products you want to update its quantity in your body request, where it will process the update procedure and then execute later on.\n",
        "operationId": "post-products-quantities-bulk",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/products/quantities/bulkSkus": {
      "post": {
        "tags": [
          "Product Quantity"
        ],
        "summary": "Update Bulk Quantities by SKU",
        "description": "You can update **unlimited** bulk quantities by providing the SKUs of the products you want to update its quantity as aquery parameter.",
        "operationId": "update-multiple-products-quantities-bySkus",
        "security": [
          {
            "OAuth": [
              "ProductsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/categories": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "List Categories",
        "description": "You can list all categories related to your store directly from this endpoint. Also, it allows you to filter them using a keyword, the endpoint would return any category which name matches this keyword.\n\n",
        "operationId": "List-Categories",
        "security": [
          {
            "OAuth": [
              "CategoriesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Categories"
        ],
        "summary": "Create Category",
        "description": "This endpoint allows you to create a new category and return the category id and its details.\n\n",
        "operationId": "Create-Category",
        "security": [
          {
            "OAuth": [
              "CategoriesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/categories/{category}": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "Category Details",
        "description": "This endpoint allows you to return the complete details for a specific category by providing the ID of the category you want to get its details in the *category* path parameter.\n\n",
        "operationId": "Category-Details",
        "security": [
          {
            "OAuth": [
              "CategoriesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Categories"
        ],
        "summary": "Update Category",
        "description": "This endpoint allows you to update category details by providing the ID of the category you want to update its details in the *category* path parameter.\n\n",
        "operationId": "Update-Category",
        "security": [
          {
            "OAuth": [
              "CategoriesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Categories"
        ],
        "summary": "Delete Category",
        "description": "This endpoint allows you to delete a specific category by providing the ID of the category you want to delete in the *category* path parameter.",
        "operationId": "Delete-Category",
        "security": [
          {
            "OAuth": [
              "CategoriesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/categories/{category}/children": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "Category Children",
        "description": "You can return specific category children by providing the ID of the category you want to get its children in the *category* path parameter.",
        "operationId": "Category-Children",
        "security": [
          {
            "OAuth": [
              "CategoriesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/brands": {
      "get": {
        "tags": [
          "Brands"
        ],
        "summary": "List Brands",
        "description": "You can list all brands related to your store directly from this endpoint. Also, it allows you to filter them using a keyword, the endpoint would return any brand which name matches this keyword.\n\n",
        "operationId": "List-Brands",
        "security": [
          {
            "OAuth": [
              "BrandsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Brands"
        ],
        "summary": "Create Brand",
        "description": "This endpoint allows you to create a new brand and return the brand id and its details.",
        "operationId": "Create-Brand",
        "security": [
          {
            "OAuth": [
              "BrandsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/brands/{brand}": {
      "get": {
        "tags": [
          "Brands"
        ],
        "summary": "Brand Details",
        "description": "This endpoint allows you to return the complete details for a specific brand by providing the ID of the brand you want to get its details in the *brand* path parameter.\n\n",
        "operationId": "Brand-Details",
        "security": [
          {
            "OAuth": [
              "BrandsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Brands"
        ],
        "summary": "Update Brand",
        "description": "This endpoint allows you to update brand details by providing the ID of the brand you want to update its details in the *brand* path parameter.\n\n",
        "operationId": "Update-Brand",
        "security": [
          {
            "OAuth": [
              "BrandsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Brands"
        ],
        "summary": "Delete Brand",
        "description": "This endpoint allows you to delete a specific brand by providing the ID of the brand you want to delete in the *brand* path parameter.\n\n",
        "operationId": "Delete-Brand",
        "security": [
          {
            "OAuth": [
              "BrandsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/specialoffers": {
      "get": {
        "tags": [
          "Special Offers"
        ],
        "summary": "List Special Offers",
        "description": "You can list all special offers related to your store directly from this endpoint. \n\n",
        "operationId": "List-Special-Offers",
        "security": [
          {
            "OAuth": [
              "SpecialOffersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Special Offers"
        ],
        "summary": "Create Special Offer",
        "description": "This endpoint allows you to create a new special offer and return the created special offer id and its details.\n\n>💡 __Note__\n>\n> More details of body samples of differnt types of offers are listed in [this link](https://wiki.salla.one/share/83082619-339f-40e5-a7e9-a116f855f5bc).",
        "operationId": "Create-Special-Offer",
        "security": [
          {
            "OAuth": [
              "SpecialOffersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/specialoffers/{specialoffer}": {
      "get": {
        "tags": [
          "Special Offers"
        ],
        "summary": "Show Special Offer",
        "description": "This endpoint allows you to return the complete details for a specific special offer by providing the ID of the special offer you want to get its details in the *specialoffer* path parameter.\n\n",
        "operationId": "Show-Special-Offer",
        "security": [
          {
            "OAuth": [
              "SpecialOffersReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Special Offers"
        ],
        "summary": "Update Special Offer",
        "description": "This endpoint allows you to update special offer details by providing the ID of the special offer you want to update its details in the *specialoffer* path parameter.",
        "operationId": "Update-Special-Offer",
        "security": [
          {
            "OAuth": [
              "SpecialOffersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Special Offers"
        ],
        "summary": "Destroy Special Offer",
        "description": "This endpoint allows you to delete a specific special offer by providing the ID of the special offer you want to delete in the *specialoffer* path parameter.\n\n",
        "operationId": "Destroy-Special-Offer",
        "security": [
          {
            "OAuth": [
              "SpecialOffersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/specialoffers/{offer}/status": {
      "put": {
        "tags": [
          "Special Offers"
        ],
        "summary": "Change Special Offer Status",
        "description": "You can update specific special offer status by providing the ID of the special offer you want to update its status in the *offer* path parameter.\n\n",
        "operationId": "Change-Special-Offer-Status",
        "security": [
          {
            "OAuth": [
              "SpecialOffersReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/branches": {
      "get": {
        "tags": [
          "Branches"
        ],
        "summary": "List Branches",
        "description": "You can list all branches related to your store directly from this endpoint.\n\n",
        "operationId": "List-Branches",
        "security": [
          {
            "OAuth": [
              "BranchesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Branches"
        ],
        "summary": "Create Branch",
        "description": "This endpoint allows you to create a new branch and return the created branch id and its details.\n\n",
        "operationId": "Create-Branch",
        "security": [
          {
            "OAuth": [
              "BranchesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/branches/{branch}": {
      "get": {
        "tags": [
          "Branches"
        ],
        "summary": "Branch Details",
        "description": "This endpoint allows you to return the complete details for a specific branch by providing the ID of the branch you want to get its details in the *branch* path parameter.",
        "operationId": "Branch-Details",
        "security": [
          {
            "OAuth": [
              "BranchesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Branches"
        ],
        "summary": "Update Branch",
        "description": "This endpoint allows you to update branch details by providing the ID of the branch you want to update its details in the *branch* path parameter.",
        "operationId": "Update-Branch",
        "security": [
          {
            "OAuth": [
              "BranchesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Branches"
        ],
        "summary": "Delete Branch",
        "description": "This endpoint allows you to delete a specific branch by providing the ID of the branch you want to delete in the *branch* path parameter.",
        "operationId": "Delete-Branch",
        "security": [
          {
            "OAuth": [
              "BranchesReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/countries": {
      "get": {
        "tags": [
          "Countries"
        ],
        "summary": "List Countries",
        "description": "This endpoint allows you to list all available countries. \n\n",
        "operationId": "List-Countries",
        "security": [
          {
            "OAuth": [
              "CountriesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/countries/{country}": {
      "get": {
        "tags": [
          "Countries"
        ],
        "summary": "Country Details",
        "description": "This endpoint allows you to return the complete details for a specific country by providing the ID of the country you want to get its details in the *country* path parameter.",
        "operationId": "Country-Details",
        "security": [
          {
            "OAuth": [
              "CountriesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/countries/{country}/cities": {
      "get": {
        "tags": [
          "Cities"
        ],
        "summary": "List Cities",
        "description": "This endpoint allows you to list all available cities for a specific country by providing the ID of the country you want to get its cities in the *country* path parameter.\n\n>💡 __Note__\n>\n> Country details will also be returned in the payload.",
        "operationId": "List-Cities",
        "security": [
          {
            "OAuth": [
              "CountriesReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipments": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "summary": "List Shipments",
        "description": "You can list all shipments related to your store directly from this endpoint. Also, it allows you to filter them using by shipping company slug.",
        "operationId": "get-shipments",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Shipments"
        ],
        "summary": "Create Shipment",
        "description": "This endpoint allows you to create a shipment related to your store directly from this endpoint.",
        "operationId": "post-shipments",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipments/{shipment_id}": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "summary": "Shipment Details",
        "description": "This endpoint allows you to return the complete details for a specific shipment by providing the ID of the shipment you want to get its details in the shipment path parameter.",
        "operationId": "get-shipments-shipment_id",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Shipments"
        ],
        "summary": "Update Shipment Details",
        "description": "You can update specific Shipment Details by providing the ID of the shipment you want to update its details.",
        "operationId": "put-shipments-shipment_id",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipments/{shipment_id}/cancel": {
      "post": {
        "tags": [
          "Shipments"
        ],
        "summary": "Cancel Shipments",
        "description": "You can cancel specific Shipment by providing the ID of the shipment you want to cancel.",
        "operationId": "post-shipments-cancel-shipment_id",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipments/{shipment_id}/return": {
      "post": {
        "tags": [
          "Shipments"
        ],
        "summary": "Return Shipments",
        "description": "You can return specific Shipment by providing the ID of the shipment you want to return.",
        "operationId": "post-shipments-shipment_id-return",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipments/{shipment_id}/tracking": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "summary": "Shipment Tracking",
        "description": "This endpoint allows you to fetch tracking details for a specific shipment by providing the ID of the shipment in the path parameter.",
        "operationId": "get-shipments-shipment_id-tracking",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipping/companies/": {
      "get": {
        "tags": [
          "Shipping Companies"
        ],
        "summary": "List Shipping Companies",
        "description": "This endpoint allows you to list all active shipping companies for your store.\n \n  - ***manual*** : which means that the shipping company is from the merchant side (not available to be linked from salla dashboard)\n\n  - ***api*** : which means it has been linked through salla.\n  \n ",
        "operationId": "list-shipping-companies",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Shipping Companies"
        ],
        "summary": "Create Shipping Company",
        "description": " This endpoint allows you to create a **custom** shipping company.",
        "operationId": "post-shipping-companies",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipping/companies/{company_id}": {
      "get": {
        "tags": [
          "Shipping Companies"
        ],
        "summary": "Shipping Company Details",
        "description": "This endpoint allows you to fetch details of shipping companies for your store.\n\n  ",
        "operationId": "get-shipping-companies-company_id",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Shipping Companies"
        ],
        "summary": "Update Shipping Company",
        "description": "This endpoint allows you to update a **custom** shipping company for your store.\n\n> 💡 __Note__\n>\n> You __can't__ update a Shipping Company with `activation_type` set to `api`.  \n\n  ",
        "operationId": "put-shipping-companies",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Shipping Companies"
        ],
        "summary": "Delete Shipping Company",
        "description": "This endpoint allows you to delete a **custom** shipping company for your store.\n\n ",
        "operationId": "delete-shipping-companies",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipping/rules": {
      "get": {
        "tags": [
          "Shipping Rules"
        ],
        "summary": "List Shipping Rules",
        "description": "This endpoint allows you to fetch a list of shipping rules.",
        "operationId": "get-shipping-rules",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipping/rules/{ShippingRule_id}": {
      "get": {
        "tags": [
          "Shipping Rules"
        ],
        "summary": "Shipping Rule Details",
        "description": "This endpoint allows you to show details in regards to a specific new shipping rule.",
        "operationId": "get-shipping-rules-ShippingRule.id",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Shipping Rules"
        ],
        "summary": "Delete Shipping Rule",
        "description": "This endpoint allows you to delete an existing shipping rule.\n\n",
        "operationId": "delete-shipping-rules-ShippingRule.id",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipping/zones": {
      "get": {
        "tags": [
          "Shipping Zones"
        ],
        "summary": "List Shipping Zones",
        "description": "This endpoint allows you to list all __Custom__ Shipping Zones.\n\n",
        "operationId": "get-shipping-zones",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Shipping Zones"
        ],
        "summary": "Create Shipping Zone",
        "description": "This endpoint allows you to create a __Custom__ Shipping Zone.\n\n> 💡 __Note__\n>\n> If you ship to every country and city, set the `country` and `city` IDs to `-1`. Therefore, the variables `code` and `mobile_code` will _NOT_ appear in the response if set to `-1`.",
        "operationId": "post-shipping-zones",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/shipping/zones/{zone_id}": {
      "get": {
        "tags": [
          "Shipping Zones"
        ],
        "summary": "Shipping Zone Details",
        "description": "This endpoint allows you to fetch a specific __Custom__ Shipping Zone.\n\n",
        "operationId": "get-shipping-zones-zone_id",
        "security": [
          {
            "OAuth": [
              "ShippingsReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Shipping Zones"
        ],
        "summary": "Update Shipping Zone",
        "description": "This endpoint allows you to update a specific __Custom__ Shipping Zone.\n\n> 💡 __Note__\n>\n> If you ship to every country and city, set the `country` and `city` IDs to `-1`. Therefore, the variables `code` and `mobile_code` will __NOT__ appear in the response if set to `-1`.\n",
        "operationId": "update-shipping-zones",
        "security": [
          {
            "OAuth": [
              "ShippingsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Shipping Zones"
        ],
        "summary": "Delete Shipping Zone",
        "description": "This endpoint allows you to delete a specific __Custom__ Shipping Zone.\n\n",
        "operationId": "delete-shipping-zones-zone_id",
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/dns-records": {
      "get": {
        "tags": [
          "DNS Records"
        ],
        "summary": "List DNS Records",
        "description": "Managing DNS records for a Salla store via the API. This endpoint involves programmatically retrieving all of the DNS records, such as A, CNAME, MX, and TXT records.",
        "operationId": "get-dns_records",
        "security": [
          {
            "OAuth": [
              "DNSRecordsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "DNS Records"
        ],
        "summary": "Create DNS Record",
        "description": "Managing DNS records for a Salla store via the API. This endpoint involves programmatically creating DNS records such as A, CNAME, MX, and TXT records.",
        "operationId": "post-dns_records",
        "security": [
          {
            "OAuth": [
              "DNSRecordsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/dns-records/{dns_id}": {
      "delete": {
        "tags": [
          "DNS Records"
        ],
        "summary": "Delete DNS Record",
        "description": "Managing DNS records for a Salla store via the API. This endpoint involves programmatically deleting DNS records such as A, CNAME, MX, and TXT records.",
        "operationId": "delete-dns_records-dns_id",
        "security": [
          {
            "OAuth": [
              "DNSRecordsReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/languages": {
      "post": {
        "tags": [
          "Languages"
        ],
        "summary": "Activate/Deactivate Language",
        "description": "This endpoint allows you to activate or deactivate a specific language using the `locales` object in the body request.\n\n",
        "operationId": "post-languages",
        "security": [
          {
            "OAuth": [
              "MetaDataReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/currencies": {
      "get": {
        "tags": [
          "Currencies"
        ],
        "summary": "List Currencies",
        "description": "This endpoint allows you to fetch and display a list of all currencies alongside their details, such as `name`, `code`, `symbol` and `status`.\n\n",
        "operationId": "get-currencies",
        "security": [
          {
            "OAuth": [
              "MetaDataReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Currencies"
        ],
        "summary": "Activate Currency(ies)",
        "description": "This endpoint allows you to activate a specific currency.\n\n",
        "operationId": "post-currencies",
        "security": [
          {
            "OAuth": [
              "MetaDataReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/currencies/available": {
      "get": {
        "tags": [
          "Currencies"
        ],
        "summary": "List Available Currencies",
        "description": "This endpoint allows you to fetch and display a list of available currencies alongside their details.\n\n",
        "operationId": "get-currencies-available",
        "security": [
          {
            "OAuth": [
              "MetaDataReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "List Employees",
        "description": "This endpoint allows you to fetch a list of your Store Employees.",
        "operationId": "get-users",
        "security": [],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/oauth2/user/info": {
      "get": {
        "tags": [
          "Store"
        ],
        "summary": "User Information",
        "description": "This endpoint allows you to fetch User information based on the [Access Token](https://salla.dev/blog/oauth-2-0-in-action-with-salla/) you have received, with a detailed response showcasing Store information.\n\n> 💡 __Note__\n>\n> ✅ The `ID` , `email`, `name`, `mobile` and `role` are the information of the user who _authorized_ the app to be installed and it is __not__ always the store owner as it can be one of the store team.\n",
        "operationId": "get-user-info",
        "security": [],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/seo": {
      "get": {
        "tags": [
          "SEO"
        ],
        "summary": "List SEO Settings",
        "description": "This endpoint allows you to show your Store's SEO Settings, such as Title, Keywords, and Description.",
        "operationId": "get-seo",
        "security": [
          {
            "OAuth": [
              "MetaDataReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "SEO"
        ],
        "summary": "Update SEO Settings",
        "description": "This endpoint allows you to update your Store's Seo Settings, such as Title, Keywords, and Description.\n\n",
        "operationId": "put-seo",
        "security": [
          {
            "OAuth": [
              "MetaDataReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/advertisements": {
      "get": {
        "tags": [
          "Advertisements"
        ],
        "summary": "List Advertisements",
        "description": "This endpoint allows you to list all of the advertisement posts of the store.\n\n",
        "operationId": "get-advertisements",
        "security": [
          {
            "OAuth": []
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Advertisements"
        ],
        "summary": "Create Advertisement",
        "description": "This endpoint allows you to create an advertisement post of the store on its pages.\n\n",
        "operationId": "post-advertisements",
        "security": [
          {
            "OAuth": []
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/advertisements/{advertisements_id}": {
      "get": {
        "tags": [
          "Advertisements"
        ],
        "summary": "Advertisement Details",
        "description": "This endpoint allows you to list an existing advertisement post by providing its ID as a path parameter.\n\n",
        "operationId": "get-advertisements-advertisements_id",
        "security": [
          {
            "OAuth": []
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Advertisements"
        ],
        "summary": "Update Advertisement",
        "description": "This endpoint allows you to update an existing advertisement post by providing its ID as a path parameter.\n\n",
        "operationId": "put-advertisements-advertisements_id",
        "security": [
          {
            "OAuth": []
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Advertisements"
        ],
        "summary": "Delete Advertisement",
        "description": "This endpoint allows you to delete an existing advertisement post by providing its ID as a path parameter.\n\n",
        "operationId": "delete-advertisements-advertisements_id",
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/affiliates": {
      "get": {
        "tags": [
          "Affiliates"
        ],
        "summary": "List Affiliates",
        "description": "This endpoint allows you to fetch a list of marketing affiliates.\n\n",
        "operationId": "get-affiliates",
        "security": [
          {
            "OAuth": [
              "MarketingReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Affiliates"
        ],
        "summary": "Create Affiliate",
        "description": "This endpoint allows you to create a marketing affiliate.",
        "operationId": "post-affiliates",
        "security": [
          {
            "OAuth": [
              "MarketingReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/affiliates/{affiliates_id}": {
      "get": {
        "tags": [
          "Affiliates"
        ],
        "summary": "Affiliate Details",
        "description": "This endpoint allows you to fetch details regarding an affiliate via its ID.",
        "operationId": "get-affiliates-affiliates.id",
        "security": [
          {
            "OAuth": [
              "MarketingReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Affiliates"
        ],
        "summary": "Update Affiliate",
        "description": "This endpoint allows you to update details regarding an affiliate via its ID.",
        "operationId": "put-affiliates-affiliates.id",
        "security": [
          {
            "OAuth": [
              "MarketingReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Affiliates"
        ],
        "summary": "Delete Affiliate",
        "description": "This endpoint allows you to delete an affiliate via its ID.",
        "operationId": "delete-affiliates-affiliates.id",
        "security": [
          {
            "OAuth": [
              "MarketingReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/coupons": {
      "get": {
        "tags": [
          "Coupons"
        ],
        "summary": "List Coupons",
        "description": "This endpoint allows you to fetch a list of coupons.",
        "operationId": "get-coupons",
        "security": [
          {
            "OAuth": [
              "MarketingReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "post": {
        "tags": [
          "Coupons"
        ],
        "summary": "Create Coupon",
        "description": "This endpoint allows you to create Single Coupon, and Group Coupons.\n\n<!-- theme: warning -->\n> 💡 __Note__\n>\n> Although the response payload you will be receiving of the two coupon-types at once, each has its own required Body Requests.\n\n<!--\ntype: tab\ntitle: Single Coupon\n-->\n\nWhen creating a `Single Coupon`, ensure that you are sending the following required variables:\n\n| Attribute | Type | Is Required |\n| -- | -- | -- |\n| `code` | string | Yes |\n| `typ[...]",
        "operationId": "post-coupons",
        "security": [
          {
            "OAuth": [
              "MarketingReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/coupons/{coupon_id}": {
      "get": {
        "tags": [
          "Coupons"
        ],
        "summary": "Coupon Details",
        "description": " This endpoint allows you to fetch details regarding a coupon via its ID.\n\n",
        "operationId": "get-coupons-coupon.id",
        "security": [
          {
            "OAuth": [
              "MarketingReadOnly"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "put": {
        "tags": [
          "Coupons"
        ],
        "summary": "Update Coupon",
        "description": "This endpoint allows you to update details regarding a coupon via its ID.\n\n",
        "operationId": "put-coupons-coupon.id",
        "security": [
          {
            "OAuth": [
              "MarketingReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      },
      "delete": {
        "tags": [
          "Coupons"
        ],
        "summary": "Delete Coupon",
        "description": " This endpoint allows you to delete a coupon via its ID.\n\n",
        "operationId": "delete-coupons-coupon.id",
        "security": [
          {
            "OAuth": [
              "MarketingReadWrite"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    },
    "/store/info": {
      "get": {
        "tags": [
          "Store"
        ],
        "summary": "Store Info Details",
        "description": "This endpoint allows you to return the Store's detail information.",
        "operationId": "get-store-info",
        "servers": [
          {
            "url": "https://api.salla.dev/admin/v2",
            "description": "Production"
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Orders",
      "description": "Orders"
    },
    {
      "name": "Order Status",
      "description": "Order Status"
    },
    {
      "name": "Order Shipment",
      "description": "Order Shipment"
    },
    {
      "name": "Order Histories",
      "description": "Order Histories"
    },
    {
      "name": "Order Tags",
      "description": "Order Tags"
    },
    {
      "name": "Order Invoice",
      "description": "Order Invoice"
    },
    {
      "name": "Products",
      "description": "Products"
    },
    {
      "name": "Product Quantity",
      "description": "Product Quantity"
    },
    {
      "name": "Product Images",
      "description": "Product Images"
    },
    {
      "name": "Product Options",
      "description": "Product Options"
    },
    {
      "name": "Product Option Values",
      "description": "Product Option Values"
    },
    {
      "name": "Product Variants",
      "description": "Product Variants"
    },
    {
      "name": "Digitals Product",
      "description": "Digitals Product"
    },
    {
      "name": "Categories",
      "description": "Categories"
    },
    {
      "name": "Brands",
      "description": "Brands"
    },
    {
      "name": "Branches",
      "description": "Branches"
    },
    {
      "name": "Special Offers",
      "description": "Special Offers"
    },
    {
      "name": "Customers",
      "description": "Customers"
    },
    {
      "name": "Customer Groups",
      "description": "Customer Groups"
    },
    {
      "name": "Abandoned Carts",
      "description": "Abandoned Carts"
    },
    {
      "name": "Taxes",
      "description": "Taxes"
    },
    {
      "name": "Payments",
      "description": "Payments"
    },
    {
      "name": "Countries",
      "description": "Countries"
    },
    {
      "name": "Cities",
      "description": "Cities"
    },
    {
      "name": "Webhooks",
      "description": "Webhooks"
    }
  ],
  "components": {
    "securitySchemes": {
      "OAuth": {
        "type": "oauth2",
        "description": "You need to send the OAuth parameter as a header parameter. Use the __User Info URL__ to fetch user related information: `https://accounts.salla.sa/oauth2/user/info`.\n\nRead More on:\n\n- [OAuth in Action](https://salla.dev/blog/oauth-2-0-in-action-with-salla/)\n- [OAuth using Postman](https://salla.dev/tutorial/oauth-2-using-postman/)\n- [Authorization Documentation Reference](https://docs.salla.dev/docs/merchant/ZG9jOjI0NTA0MzI3-authorization)",
        "flows": {
          "authorizationCode": {
            "refreshUrl": "https://accounts.salla.sa/oauth2/token",
            "authorizationUrl": "https://accounts.salla.sa/oauth2/auth",
            "scopes": {
              "CustomersReadOnly": "customers.read",
              "OrdersReadOnly": "orders.read",
              "CartsReadOnly": "carts.read",
              "BranchesReadOnly": "branches.read",
              "CategoriesReadOnly": "categories.read",
              "BrandsReadOnly": "brands.read",
              "ProductsReadOnly": "products.read",
              "WebhooksReadOnly": "webhooks.read",
              "PaymentsReadOnly": "payments.read",
              "TaxesReadOnly": "taxes.read",
              "SpecialOffersReadOnly": "specialoffers.read",
              "CountriesReadOnly": "countries.read",
              "SettingsReadOnly": "settings.read",
              "MetaDataReadOnly": "metadata.read",
              "ShippingsReadOnly": "shippings.read",
              "MarketingReadOnly": "marketing.read",
              "DNSRecordsReadOnly": "dns-records.read",
              "OrdersReadWrite": "orders.read_write",
              "CartsReadWrite": "carts.read_write",
              "BranchesReadWrite": "branches.read_write",
              "ProductsReadWrite": "products.read_write",
              "WebhooksReadWrite": "webhooks.read_write",
              "PaymentsReadWrite": "payments.read_write",
              "TaxesReadWrite": "taxes.read_write",
              "SpecialOffersReadWrite": "specialoffers.read_write",
              "CountriesReadWrite": "countries.read_write",
              "SettingsReadWrite": "settings.read_write",
              "MetaDataReadWrite": "metadata.read_write",
              "ShippingsReadWrite": "shippings.read_write",
              "CustomersReadWrite": "customers.read_write",
              "CategoriesReadWrite": "categories.read_write",
              "BrandsReadWrite": "brands.read_write",
              "MarketingReadWrite": "marketing.read_write",
              "DNSRecordsReadWrite": "dns-records.read_write"
            },
            "tokenUrl": "https://accounts.salla.sa/oauth2/token"
          }
        }
      }
    }
  }
}